version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: DarkAuth
      POSTGRES_USER: DarkAuth
      POSTGRES_PASSWORD: DarkAuth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U DarkAuth -d DarkAuth"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
