import Layout from "../../components/Layout";
import PageHero from "../../components/PageHero";
import CodeBlock from "../../components/CodeBlock";
import CTABlock from "../../components/CTABlock";
import RelatedLinks from "../../components/RelatedLinks";
import Accordion from "../../components/Accordion";
import styles from "../../pages/Security.module.css";

const authRequestExample = `GET /api/authorize?
  client_id=my_app
  &response_type=code
  &redirect_uri=https%3A%2F%2Fapp.example.com%2Fcallback
  &scope=openid
  &code_challenge=<S256_challenge>
  &code_challenge_method=S256
  &state=<random_state>
  &zk_pub=<base64url(JSON.stringify(JWK))>`;

const zkPubExample = `// Ephemeral ECDH P-256 keypair generated by the app
const { privateKey, publicKey } = await crypto.subtle.generateKey(
  { name: "ECDH", namedCurve: "P-256" },
  true,   // extractable
  ["deriveKey", "deriveBits"]
);

const jwk = await crypto.subtle.exportKey("jwk", publicKey);
// { kty: "EC", crv: "P-256", x: "...", y: "..." }

const zk_pub = btoa(JSON.stringify(jwk))
  .replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
// base64url(JSON.stringify(JWK))`;

const verifyExample = `// After token endpoint call returns { id_token, zk_drk_hash }
// Fragment: window.location.hash = "#drk_jwe=..."

const fragment = new URLSearchParams(window.location.hash.slice(1));
const drk_jwe_compact = fragment.get("drk_jwe");

// Verify integrity before decrypting
const jweBytes = new TextEncoder().encode(drk_jwe_compact);
const hashBuffer = await crypto.subtle.digest("SHA-256", jweBytes);
const computed_hash = base64url(new Uint8Array(hashBuffer));

if (computed_hash !== zk_drk_hash) {
  throw new Error("DRK JWE integrity check failed");
}

// Now safe to decrypt
const drk = await decryptJWE(drk_jwe_compact, ephemeralPrivateKey);`;

export default function ZeroKnowledge() {
  return (
    <Layout>
      <PageHero
        eyebrow="Security"
        title="The ZK Extension — client-side key delivery"
        sub="How DarkAuth delivers an encryption key to your app through the login flow, without the server ever seeing it."
      />
      <div className="container">
        <div style={{ padding: "3rem 0 4rem" }}>

          <section className={styles.section}>
            <h2 style={{ fontSize: "1.4rem", marginBottom: "1rem" }}>Overview</h2>
            <p>
              The zero-knowledge extension (formally: the OIDC ZK Key Delivery Extension) is an opt-in feature that adds a cryptographic key handoff to the standard OIDC Authorization Code + PKCE flow. It is designed for applications that need both identity (who is logged in) and an encryption key (to encrypt or decrypt user data) — delivered through a single login.
            </p>
            <p>
              The critical design constraint: <strong>the authorization server stores and returns only a hash of the key JWE — never the JWE itself.</strong> The JWE travels only in the URL fragment, which HTTP spec guarantees is not transmitted to the server.
            </p>
            <div style={{ marginTop: "1rem", background: "var(--secondary-dim)", border: "1px solid rgba(242,177,13,0.25)", borderRadius: "var(--radius)", padding: "1rem 1.25rem" }}>
              <strong style={{ color: "var(--secondary)", fontSize: "0.8rem", textTransform: "uppercase", letterSpacing: "0.08em" }}>Trust boundary</strong>
              <p style={{ marginTop: "0.5rem", fontSize: "0.9rem" }}>
                The ZK extension protects against database exfiltration and server-side reads. It does not protect against malicious JavaScript on the auth UI or RP origin, XSS, compromised browser extensions, or a device that is fully compromised. These are the out-of-scope threats for any hosted-web ZK system.
              </p>
            </div>
          </section>

          <section className={styles.section}>
            <h2 style={{ fontSize: "1.4rem", marginBottom: "1rem" }}>Client registration requirements</h2>
            <p>A client must be registered with the following metadata to use ZK delivery:</p>
            <ul style={{ paddingLeft: "1.5rem", display: "flex", flexDirection: "column", gap: "0.5rem", margin: "0.75rem 0" }}>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}><code>zk_delivery: "fragment-jwe"</code> — opt-in to ZK delivery</li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}><code>key_delivery_version: "v1-drk"</code> — DRK payload (current v1)</li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}><code>allowed_jwe_algs: ["ECDH-ES"]</code></li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}><code>allowed_jwe_encs: ["A256GCM"]</code></li>
            </ul>
            <p>Standard (non-ZK) clients are completely unaffected. The extension is backward-compatible.</p>
          </section>

          <section className={styles.section}>
            <h2 style={{ fontSize: "1.4rem", marginBottom: "1rem" }}>Step 1 — Supply zk_pub in the authorization request</h2>
            <p>
              The app generates an ephemeral ECDH P-256 keypair. The public key is JSON-encoded as a JWK, then base64url-encoded, and supplied as the <code>zk_pub</code> parameter.
            </p>
            <CodeBlock code={zkPubExample} lang="JavaScript" />
            <CodeBlock code={authRequestExample} lang="Authorization request" />
            <Accordion label="zk_pub validation requirements" badge="Server-side">
              <ul style={{ paddingLeft: "1.5rem", display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                <li style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>Must be valid <code>base64url(JSON.stringify(JWK))</code></li>
                <li style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>JWK must contain <code>kty="EC"</code>, <code>crv="P-256"</code>, valid <code>x</code> and <code>y</code></li>
                <li style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>x and y must be 32-byte base64url-encoded values representing valid P-256 curve points</li>
                <li style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>Server must verify the point lies on the P-256 curve</li>
                <li style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>Must NOT contain private key component (<code>d</code> field)</li>
                <li style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>Malformed, invalid, or weak keys: server returns <code>invalid_request</code></li>
                <li style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>Server must NOT log <code>zk_pub</code> or any derived cryptographic material</li>
              </ul>
            </Accordion>
          </section>

          <section className={styles.section}>
            <h2 style={{ fontSize: "1.4rem", marginBottom: "1rem" }}>Step 2 — Browser builds and delivers the JWE</h2>
            <p>
              After the user authenticates via OPAQUE, the browser (DarkAuth auth UI) performs the key operations:
            </p>
            <ol style={{ paddingLeft: "1.5rem", display: "flex", flexDirection: "column", gap: "0.5rem", margin: "0.75rem 0" }}>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Derives <code>MK → KW</code> from the OPAQUE <code>export_key</code> via HKDF-SHA256</li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Fetches and decrypts <code>WRAPPED_DRK</code> using <code>KW</code> — obtains the DRK locally</li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Constructs <code>drk_jwe = ECDH-ES + A256GCM(DRK, zk_pub)</code> with AAD = <code>{"{"}"sub, client_id{"}"}</code></li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Computes <code>drk_hash = base64url(SHA-256(drk_jwe))</code></li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Sends <code>POST /api/authorize/finalize {"{"} request_id, drk_hash {"}"}</code> — server stores only the hash</li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Redirects to <code>redirect_uri#drk_jwe=&lt;compact JWE&gt;</code> — fragment never sent to server</li>
            </ol>
          </section>

          <section className={styles.section}>
            <h2 style={{ fontSize: "1.4rem", marginBottom: "1rem" }}>Step 3 — App verifies and decrypts</h2>
            <p>
              After the redirect, the app calls the token endpoint and receives <code>zk_drk_hash</code>. It must verify the hash matches the fragment JWE before decrypting.
            </p>
            <CodeBlock code={verifyExample} lang="JavaScript" />
            <p>
              If the hash does not match, the app must reject the JWE. This prevents an attacker who can inject content into the fragment from substituting a different key.
            </p>
          </section>

          <section className={styles.section}>
            <h2 style={{ fontSize: "1.4rem", marginBottom: "1rem" }}>Key custody guidance</h2>
            <ul style={{ paddingLeft: "1.5rem", display: "flex", flexDirection: "column", gap: "0.5rem" }}>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Default: memory-only DRK custody in the RP app. Page reload triggers a fresh ZK authorization.</li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>After callback handling: remove the <code>#drk_jwe</code> fragment from the URL and clear the ephemeral ZK private key.</li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Persistent plaintext DRK storage in localStorage, sessionStorage, or JS-readable cookies must NOT be described as cryptographic protection.</li>
              <li style={{ fontSize: "0.9rem", color: "var(--text-muted)" }}>Each <code>zk_pub</code> should be a fresh ephemeral key — reuse across authorizations increases linkability.</li>
            </ul>
          </section>

          <CTABlock
            title="Read the full whitepaper"
            desc="The complete security whitepaper covers all flows, threat model, and auditor checklist."
            showDocker={false}
            primaryLabel="Security whitepaper"
            primaryTo="/security/whitepaper"
            secondaryLabel="Source on GitHub"
            secondaryHref="https://github.com/puzed/darkauth"
          />

          <RelatedLinks links={[
            { label: "ZK key delivery feature", to: "/features/zero-knowledge-keys" },
            { label: "Security whitepaper", to: "/security/whitepaper" },
            { label: "How it works", to: "/how-it-works" },
            { label: "Developer SDK", to: "/developers/sdk" },
          ]} />
        </div>
      </div>
    </Layout>
  );
}
