name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: DarkAuth
          POSTGRES_PASSWORD: DarkAuth_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U DarkAuth" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: DarkAuth
      POSTGRES_PASSWORD: DarkAuth_password
      NODE_ENV: test
      CI: true
      PW_BROWSER_CHANNEL: chrome
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm run test -w @DarkAuth/api -w @darkauth/client -w @DarkAuth/md-to-pdf -w opaque-ts -w @DarkAuth/user-ui
